---
openapi: 3.0.1
info:
  title: API V1
  version: v1
consumes:
- application/json
produces:
- application/json
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    bearer:
      type: bearer
      name: Authorization
      in: header
security:
  bearerAuth: []
paths:
  "/api/v1/users":
    post:
      summary: Signup
      tags:
      - Authentication
      security: []
      parameters: []
      responses:
        '200':
          description: Sign up
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    password_confirmation:
                      type: string
                  required:
                  - email
                  - password
                  - password_confirmation
  "/api/v1/oauth/token":
    post:
      summary: Login
      tags:
      - Authentication
      security: []
      parameters: []
      responses:
        '200':
          description: Login
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                grant_type:
                  type: string
                  example: password
              required:
              - email
              - password
              - grant_type
  "/api/v1/questions":
    get:
      summary: Get All Questions
      tags:
      - Questionnaire
      security:
      - bearerAuth: []
      responses:
        '200':
          description: List Found
        '422':
          description: Invalid request
  "/api/v1/attempts":
    post:
      summary: Attempt Questionnaire
      tags:
      - Questionnaire
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: Attempted
        '422':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                answers:
                  type: array
                  items:
                    type: object
                    properties:
                      question_id:
                        type: integer
                      answer_text:
                        type: string
                      points:
                        type: integer
                      total_points:
                        type: integer
servers:
- url: http://localhost:3000
- url: https://personality-server.herokuapp.com
